### ISSUE TITLE
Improve upsert

### ISSUE THREAD

**Issue by me** [deliveroo/materialist#7]
The current implementation of upsert is vulnerable to a race condition if two jobs for the same entity are processed at the same time (`find_or_initialize_by` will "initialize" for both, but the second will fail because the primary key is not unique.

It should at least `retry` on `ActiveRecord::RecordNotUnique` errors; but better would be to use proper PostgreSQL upserts with https://github.com/jesjos/active_record_upsert (or our fork https://github.com/deliveroo/active_record_upsert which has a few additional features, until they get merged upstream).

**Comment by mvalipour** [comment]
Very good point, we definitely need to handle this case gracefully.

However, I'm trying to not have a dependency to ActiveRecord here (specially a specific error in there -- i.e. `RecordNotUnique`). Plus if you have uniqueness constraint on your entity, you wouldn't get that error and get an `InvalidRecord` error instead (and that could be raised by all other sorts of validation logic).

The reality is that if/when race condition happens, we don't actually need to do anything on the second one -- because events don't carry state and both events will end-up fetching the same resource.

So we have two options here:

- Use a distributed lock on the `url` to avoid race condition -- via redis?
- Let that fail and retried another time

Thoughts?

**Comment by me** [comment]
Right! But you already have an implicit dependency on ActiveRecord (by expecting the models to conform to the ActiveRecord interface); so I think you could make it explicit.

It is not necessarily true that we don't need to do anything on the second one in case of errors. A possible flow is
- update 1
- event 1 processing, fetch (update 1) `find_or_initialize_by` called
- update 2
- event 2 processing, fetch (update 2) `find_or_initialize_by` called
- event 1 saved
- event 2 save fails, second update is lost

This would seem far fetched but we were actually seeing it happen in production relatively often, causing out-of-sync issues.

**Comment by mvalipour** [comment]
@me how about the argument around the exceptions not being conclusive? (i.e. `RecordNotUnique` and `RecordInvalid` don't always mean what we think they would).

I'm really tempted by the idea of [Redis Lock](https://github.com/leandromoreira/redlock-rb). what do you think?

**Comment by me** [comment]
I'm not sure... I see that in the general case `RecordNotUnique` could be a different failure; in practice though, since our models are simple "caches", we would expect any upstream update to replicate correctly. In case, we could make sure to only `retry` once. However, my preferred solution would definitely be native upsert (`on conflict update`) which will avoid the need for any error catching.

Personally I would definitely avoid introducing a locking mechanism: it would massively increase the complexity and the potential for things to go wrong.

**Comment by mvalipour** [comment]
I think you convinced me 😛 

Regarding the `upsert`, it would be great if we don't have a hard dependency on PG.
There seem to be an [awesome library for upsert](https://github.com/seamusabshere/upsert) however I'm not convinced we need it here so desparately (considering how much overhead it may add)

I will go ahead and implement a basic retry logic.

**Comment by me** [comment]
I see! Note that the library above doesn't do native upsert, so it's going to be significantly slower - I guess it depends on the app how much that matters!
